<a href="https://colab.research.google.com/github/SuminPark-02/AIpython/blob/main/250509.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [1]:
pip install numpy

In [2]:
import numpy as np
print(np.__version__)

2.0.2


In [3]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [4]:
b = np.array([[1, 2], [3, 4]])
print(b)

[[1 2]
 [3 4]]


In [5]:
type(a)

numpy.ndarray

In [6]:
c = [1, 2, 3]
type(c)

list

# Numpy 실습 문제

In [20]:
# 1번
a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [21]:
# 2번
b = np.arange(2, 11, 2)
print(b)

[ 2  4  6  8 10]


In [22]:
# 3번
c = np.array([2, 4, 6])
d = np.array([10, 20, 30])

r = c * d
print(r)

[ 20  80 180]


In [23]:
# 4번
f = r[r > 20]
print(f)

[ 80 180]


# Pandas

In [53]:
pip install pandas

In [54]:
import pandas as pd
print(pd.__version__)

2.2.2


In [27]:
s = pd.Series([10, 20, 30, 40])
print(s)
print(type(s))

0    10
1    20
2    30
3    40
dtype: int64
<class 'pandas.core.series.Series'>


In [28]:
data = {
    '이름': ['홍길동', '김철수', '이영희'],
    '나이': [25, 30, 27],
    '성별': ['남', '남', '여']
}

df = pd.DataFrame(data)
print(df)

    이름  나이 성별
0  홍길동  25  남
1  김철수  30  남
2  이영희  27  여


In [29]:
df.to_csv('output_students.csv', index=False)

In [33]:
df = pd.read_csv('output_students.csv')
print(df.head())

    이름  나이 성별
0  홍길동  25  남
1  김철수  30  남
2  이영희  27  여


In [55]:
df = pd.read_csv('train_and_test2.csv')
print(df.head())

   Passengerid   Age     Fare  Sex  sibsp  zero  zero.1  zero.2  zero.3  \
0            1  22.0   7.2500    0      1     0       0       0       0   
1            2  38.0  71.2833    1      1     0       0       0       0   
2            3  26.0   7.9250    1      0     0       0       0       0   
3            4  35.0  53.1000    1      1     0       0       0       0   
4            5  35.0   8.0500    0      0     0       0       0       0   

   zero.4  ...  zero.12  zero.13  zero.14  Pclass  zero.15  zero.16  Embarked  \
0       0  ...        0        0        0       3        0        0       2.0   
1       0  ...        0        0        0       1        0        0       0.0   
2       0  ...        0        0        0       3        0        0       2.0   
3       0  ...        0        0        0       1        0        0       2.0   
4       0  ...        0        0        0       3        0        0       2.0   

   zero.17  zero.18  2urvived  
0        0        0         0 

In [56]:
print(df.tail())

      Passengerid   Age      Fare  Sex  sibsp  zero  zero.1  zero.2  zero.3  \
1304         1305  28.0    8.0500    0      0     0       0       0       0   
1305         1306  39.0  108.9000    1      0     0       0       0       0   
1306         1307  38.5    7.2500    0      0     0       0       0       0   
1307         1308  28.0    8.0500    0      0     0       0       0       0   
1308         1309  28.0   22.3583    0      1     0       0       0       0   

      zero.4  ...  zero.12  zero.13  zero.14  Pclass  zero.15  zero.16  \
1304       0  ...        0        0        0       3        0        0   
1305       0  ...        0        0        0       1        0        0   
1306       0  ...        0        0        0       3        0        0   
1307       0  ...        0        0        0       3        0        0   
1308       0  ...        0        0        0       3        0        0   

      Embarked  zero.17  zero.18  2urvived  
1304       2.0        0        0   

In [57]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 28 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Passengerid  1309 non-null   int64  
 1   Age          1309 non-null   float64
 2   Fare         1309 non-null   float64
 3   Sex          1309 non-null   int64  
 4   sibsp        1309 non-null   int64  
 5   zero         1309 non-null   int64  
 6   zero.1       1309 non-null   int64  
 7   zero.2       1309 non-null   int64  
 8   zero.3       1309 non-null   int64  
 9   zero.4       1309 non-null   int64  
 10  zero.5       1309 non-null   int64  
 11  zero.6       1309 non-null   int64  
 12  Parch        1309 non-null   int64  
 13  zero.7       1309 non-null   int64  
 14  zero.8       1309 non-null   int64  
 15  zero.9       1309 non-null   int64  
 16  zero.10      1309 non-null   int64  
 17  zero.11      1309 non-null   int64  
 18  zero.12      1309 non-null   int64  
 19  zero.1

In [58]:
print(df.describe())

       Passengerid          Age         Fare          Sex        sibsp  \
count  1309.000000  1309.000000  1309.000000  1309.000000  1309.000000   
mean    655.000000    29.503186    33.281086     0.355997     0.498854   
std     378.020061    12.905241    51.741500     0.478997     1.041658   
min       1.000000     0.170000     0.000000     0.000000     0.000000   
25%     328.000000    22.000000     7.895800     0.000000     0.000000   
50%     655.000000    28.000000    14.454200     0.000000     0.000000   
75%     982.000000    35.000000    31.275000     1.000000     1.000000   
max    1309.000000    80.000000   512.329200     1.000000     8.000000   

         zero  zero.1  zero.2  zero.3  zero.4  ...  zero.12  zero.13  zero.14  \
count  1309.0  1309.0  1309.0  1309.0  1309.0  ...   1309.0   1309.0   1309.0   
mean      0.0     0.0     0.0     0.0     0.0  ...      0.0      0.0      0.0   
std       0.0     0.0     0.0     0.0     0.0  ...      0.0      0.0      0.0   
min      

In [59]:
df[df['Age'] < 20]

Passengerid   Age     Fare  Sex  sibsp  zero  zero.1  zero.2  zero.3  \
7               8   2.0  21.0750    0      3     0       0       0       0   
9              10  14.0  30.0708    1      1     0       0       0       0   
10             11   4.0  16.7000    1      1     0       0       0       0   
14             15  14.0   7.8542    1      0     0       0       0       0   
16             17   2.0  29.1250    0      4     0       0       0       0   
...           ...   ...      ...  ...    ...   ...     ...     ...     ...   
1280         1281   6.0  21.0750    0      3     0       0       0       0   
1283         1284  13.0  20.2500    0      0     0       0       0       0   
1286         1287  18.0  60.0000    1      1     0       0       0       0   
1294         1295  17.0  47.1000    0      0     0       0       0       0   
1300         1301   3.0  13.7750    1      1     0       0       0       0   

      zero.4  ...  zero.12  zero.13  zero.14  Pclass  zero.15  zero.16  \
7          0  ...        0        0        0       3        0        0   
9          0  ...        0        0        0       2        0        0   
10         0  ...        0        0        0       3        0        0   
14         0  ...        0        0        0       3        0        0   
16         0  ...        0        0        0       3        0        0   
...      ...  ...      ...      ...      ...     ...      ...      ...   
1280       0  ...        0        0        0       3        0        0   
1283       0  ...        0        0        0       3        0        0   
1286       0  ...        0        0        0       1        0        0   
1294       0  ...        0        0        0       1        0        0   
1300       0  ...        0        0        0       3        0        0   

      Embarked  zero.17  zero.18  2urvived  
7          2.0        0        0         0  
9          0.0        0        0         1  
10         2.0        0        0         1  
14         2.0        0        0         0  
16         1.0        0        0         0  
...        ...      ...      ...       ...  
1280       2.0        0        0         0  
1283       2.0        0        0         0  
1286       2.0        0        0         0  
1294       2.0        0        0         0  
1300       2.0        0        0         0  

[225 rows x 28 columns]

In [60]:
df.dropna()
print(df)

      Passengerid   Age      Fare  Sex  sibsp  zero  zero.1  zero.2  zero.3  \
0               1  22.0    7.2500    0      1     0       0       0       0   
1               2  38.0   71.2833    1      1     0       0       0       0   
2               3  26.0    7.9250    1      0     0       0       0       0   
3               4  35.0   53.1000    1      1     0       0       0       0   
4               5  35.0    8.0500    0      0     0       0       0       0   
...           ...   ...       ...  ...    ...   ...     ...     ...     ...   
1304         1305  28.0    8.0500    0      0     0       0       0       0   
1305         1306  39.0  108.9000    1      0     0       0       0       0   
1306         1307  38.5    7.2500    0      0     0       0       0       0   
1307         1308  28.0    8.0500    0      0     0       0       0       0   
1308         1309  28.0   22.3583    0      1     0       0       0       0   

      zero.4  ...  zero.12  zero.13  zero.14  Pclas

In [64]:
df.dropna(inplace=True)
print(df)

      Passengerid   Age      Fare  Sex  sibsp  zero  zero.1  zero.2  zero.3  \
0               1  22.0    7.2500    0      1     0       0       0       0   
1               2  38.0   71.2833    1      1     0       0       0       0   
2               3  26.0    7.9250    1      0     0       0       0       0   
3               4  35.0   53.1000    1      1     0       0       0       0   
4               5  35.0    8.0500    0      0     0       0       0       0   
...           ...   ...       ...  ...    ...   ...     ...     ...     ...   
1304         1305  28.0    8.0500    0      0     0       0       0       0   
1305         1306  39.0  108.9000    1      0     0       0       0       0   
1306         1307  38.5    7.2500    0      0     0       0       0       0   
1307         1308  28.0    8.0500    0      0     0       0       0       0   
1308         1309  28.0   22.3583    0      1     0       0       0       0   

      zero.4  ...  zero.12  zero.13  zero.14  Pclas

In [66]:
df.groupby('Sex')['Age'].mean()

Sex
0    30.017888
1    28.479720
Name: Age, dtype: float64